=== Vaek/MotionClassification/Data/data/placingBall/scene.dtd
<!ELEMENT scene (structure?, annotation?)>
<!ELEMENT structure (node)>
<!ELEMENT node (node*)>
<!ELEMENT annotation (node)>

<!ATTLIST scene source_fbx CDATA #REQUIRED>
<!ATTLIST node name CDATA #REQUIRED>
<!ATTLIST node path CDATA #REQUIRED>
<!ATTLIST node animationLength CDATA #REQUIRED>
<!ATTLIST node annotation(None | Hips | Spin | Spin1 | Spin2 | Neck | Head | RightShoulder | RightArm | RightArmRoll | RightForeArm | RightForeArmRoll |
RightHand | RightHandThumb1 | RightHandThumb2 | RightHandThumb3 | RightHandThumb4 | RightHandIndex1 | RightHandIndex2 |
RightHandIndex3 | RightHandIndex4 | RightHandMiddle1 | RightHandMiddle2 | RightHandMiddle3 | RightHandMiddle4 | RightHandRing1 |
RightHandRing2 | RightHandRing3 | RightHandRing4 | RightHandPinky1 | RightHandPinky2 | RightHandPinky3 | RightHandPinky4 |
LeftShoulder | LeftArm | LeftArmRoll | LeftForeArm | LeftForeArmRoll | LeftHand | LeftHandThumb1 | LeftHandThumb2 | LeftHandThumb3 |
LeftHandThumb4 | LeftHandIndex1 | LeftHandIndex2 | LeftHandIndex3 | LeftHandIndex4 | LeftHandMiddle1 | LeftHandMiddle2 |
LeftHandMiddle3 | LeftHandMiddle4 | LeftHandRing1 | LeftHandRing2 | LeftHandRing3 | LeftHandRing4 | LeftHandPinky1 |
LeftHandPinky2 | LeftHandPinky3 | LeftHandPinky4 | RightHip | RightUpLeg | RightUpLegRoll | RightLeg | RightLegRoll | RightFoot |
RightToeBase | LeftHip | LeftUpLeg | LeftUpLegRoll | LeftLeg | LeftLegRoll | LeftFoot | LeftToeBase) "None">

=== Vaek/MotionClassification/Data/data/walk/07_10.xml
<?xml version="1.0"?>
<!DOCTYPE scene SYSTEM "scene.dtd">
<scene source_fbx="./data/walk/07_10.bvh">
	<structure>
		<node name="RootNode" path="/RootNode" annotation="None">
			<node name="BVH:reference" path="/RootNode/BVH:reference" annotation="None">
				<node name="Hips" path="/RootNode/BVH:reference/Hips" annotation="None">
					<node name="LowerBack" path="/RootNode/BVH:reference/Hips/LowerBack" annotation="None">
						<node name="Spine" path="/RootNode/BVH:reference/Hips/LowerBack/Spine" annotation="None">
							<node name="Spine1" path="/RootNode/BVH:reference/Hips/LowerBack/Spine/Spine1" annotation="None">
								<node name="RightShoulder" path="/RootNode/BVH:reference/Hips/LowerBack/Spine/Spine1/RightShoulder" annotation="None">
									<node name="RightArm" path="/RootNode/BVH:reference/Hips/LowerBack/Spine/Spine1/RightShoulder/RightArm" annotation="None">
										<node name="RightForeArm" path="/RootNode/BVH:reference/Hips/LowerBack/Spine/Spine1/RightShoulder/RightArm/RightForeArm" annotation="None">
											<node name="RightHand" path="/RootNode/BVH:reference/Hips/LowerBack/Spine/Spine1/RightShoulder/RightArm/RightForeArm/RightHand" annotation="None">
												<node name="RThumb" path="/RootNode/BVH:reference/Hips/LowerBack/Spine/Spine1/RightShoulder/RightArm/RightForeArm/RightHand/RThumb" annotation="None">
													<node name="RThumb_End" path="/RootNode/BVH:reference/Hips/LowerBack/Spine/Spine1/RightShoulder/RightArm/RightForeArm/RightHand/RThumb/RThumb_End" annotation="None" />
												</node>
												<node name="RightFingerBase" path="/RootNode/BVH:reference/Hips/LowerBack/Spine/Spine1/RightShoulder/RightArm/RightForeArm/RightHand/RightFingerBase" annotation="None">
													<node name="RightHandIndex1" path="/RootNode/BVH:reference/Hips/LowerBack/Spine/Spine1/RightShoulder/RightArm/RightForeArm/RightHand/RightFingerBase/RightHandIndex1" annotation="None">
														<node name="RightHandIndex1_End" path="/RootNode/BVH:reference/Hips/LowerBack/Spine/Spine1/RightShoulder/RightArm/RightForeArm/RightHand/RightFingerBase/RightHandIndex1/RightHandIndex1_End" annotation="None" />
													</node>
												</node>
											</node>
										</node>
									</node>
								</node>
								<node name="LeftShoulder" path="/RootNode/BVH:reference/Hips/LowerBack/Spine/Spine1/LeftShoulder" annotation="None">
									<node name="LeftArm" path="/RootNode/BVH:reference/Hips/LowerBack/Spine/Spine1/LeftShoulder/LeftArm" annotation="None">
										<node name="LeftForeArm" path="/RootNode/BVH:reference/Hips/LowerBack/Spine/Spine1/LeftShoulder/LeftArm/LeftForeArm" annotation="None">
											<node name="LeftHand" path="/RootNode/BVH:reference/Hips/LowerBack/Spine/Spine1/LeftShoulder/LeftArm/LeftForeArm/LeftHand" annotation="None">
												<node name="LThumb" path="/RootNode/BVH:reference/Hips/LowerBack/Spine/Spine1/LeftShoulder/LeftArm/LeftForeArm/LeftHand/LThumb" annotation="None">
													<node name="LThumb_End" path="/RootNode/BVH:reference/Hips/LowerBack/Spine/Spine1/LeftShoulder/LeftArm/LeftForeArm/LeftHand/LThumb/LThumb_End" annotation="None" />
												</node>
												<node name="LeftFingerBase" path="/RootNode/BVH:reference/Hips/LowerBack/Spine/Spine1/LeftShoulder/LeftArm/LeftForeArm/LeftHand/LeftFingerBase" annotation="None">
													<node name="LeftHandIndex1" path="/RootNode/BVH:reference/Hips/LowerBack/Spine/Spine1/LeftShoulder/LeftArm/LeftForeArm/LeftHand/LeftFingerBase/LeftHandIndex1" annotation="None">
														<node name="LeftHandIndex1_End" path="/RootNode/BVH:reference/Hips/LowerBack/Spine/Spine1/LeftShoulder/LeftArm/LeftForeArm/LeftHand/LeftFingerBase/LeftHandIndex1/LeftHandIndex1_End" annotation="None" />
													</node>
												</node>
											</node>
										</node>
									</node>
								</node>
								<node name="Neck" path="/RootNode/BVH:reference/Hips/LowerBack/Spine/Spine1/Neck" annotation="None">
									<node name="Neck1" path="/RootNode/BVH:reference/Hips/LowerBack/Spine/Spine1/Neck/Neck1" annotation="None">
										<node name="Head" path="/RootNode/BVH:reference/Hips/LowerBack/Spine/Spine1/Neck/Neck1/Head" annotation="None">
											<node name="Head_End" path="/RootNode/BVH:reference/Hips/LowerBack/Spine/Spine1/Neck/Neck1/Head/Head_End" annotation="None" />
										</node>
									</node>
								</node>
							</node>
						</node>
					</node>
					<node name="RHipJoint" path="/RootNode/BVH:reference/Hips/RHipJoint" annotation="None">
						<node name="RightUpLeg" path="/RootNode/BVH:reference/Hips/RHipJoint/RightUpLeg" annotation="None">
							<node name="RightLeg" path="/RootNode/BVH:reference/Hips/RHipJoint/RightUpLeg/RightLeg" annotation="None">
								<node name="RightFoot" path="/RootNode/BVH:reference/Hips/RHipJoint/RightUpLeg/RightLeg/RightFoot" annotation="None">
									<node name="RightToeBase" path="/RootNode/BVH:reference/Hips/RHipJoint/RightUpLeg/RightLeg/RightFoot/RightToeBase" annotation="None">
										<node name="RightToeBase_End" path="/RootNode/BVH:reference/Hips/RHipJoint/RightUpLeg/RightLeg/RightFoot/RightToeBase/RightToeBase_End" annotation="None" />
									</node>
								</node>
							</node>
						</node>
					</node>
					<node name="LHipJoint" path="/RootNode/BVH:reference/Hips/LHipJoint" annotation="None">
						<node name="LeftUpLeg" path="/RootNode/BVH:reference/Hips/LHipJoint/LeftUpLeg" annotation="None">
							<node name="LeftLeg" path="/RootNode/BVH:reference/Hips/LHipJoint/LeftUpLeg/LeftLeg" annotation="None">
								<node name="LeftFoot" path="/RootNode/BVH:reference/Hips/LHipJoint/LeftUpLeg/LeftLeg/LeftFoot" annotation="None">
									<node name="LeftToeBase" path="/RootNode/BVH:reference/Hips/LHipJoint/LeftUpLeg/LeftLeg/LeftFoot/LeftToeBase" annotation="None">
										<node name="LeftToeBase_End" path="/RootNode/BVH:reference/Hips/LHipJoint/LeftUpLeg/LeftLeg/LeftFoot/LeftToeBase/LeftToeBase_End" annotation="None" />
									</node>
								</node>
							</node>
						</node>
					</node>
				</node>
			</node>
		</node>
	</structure>
  <annotation>
    <node name="Hips" path="/RootNode/BVH:reference/Hips" annotation="Hips">
      <node name="LowerBack" path="/RootNode/BVH:reference/Hips/LowerBack" annotation="Spin">
        <node name="Spine" path="/RootNode/BVH:reference/Hips/LowerBack/Spine" annotation="Spin1">
          <node name="Spine1" path="/RootNode/BVH:reference/Hips/LowerBack/Spine/Spine1" annotation="Spin2">
            <node name="RightShoulder" path="/RootNode/BVH:reference/Hips/LowerBack/Spine/Spine1/RightShoulder" annotation="RightShoulder">
              <node name="RightArm" path="/RootNode/BVH:reference/Hips/LowerBack/Spine/Spine1/RightShoulder/RightArm" annotation="RightArm">
                <node name="RightForeArm" path="/RootNode/BVH:reference/Hips/LowerBack/Spine/Spine1/RightShoulder/RightArm/RightForeArm" annotation="RightForeArm">
                  <node name="RightHand" path="/RootNode/BVH:reference/Hips/LowerBack/Spine/Spine1/RightShoulder/RightArm/RightForeArm/RightHand" annotation="RightHand">
                    <node name="RThumb" path="/RootNode/BVH:reference/Hips/LowerBack/Spine/Spine1/RightShoulder/RightArm/RightForeArm/RightHand/RThumb" annotation="RightHandThumb1"/>
                  </node>
                </node>
              </node>
            </node>
            <node name="LeftShoulder" path="/RootNode/BVH:reference/Hips/LowerBack/Spine/Spine1/LeftShoulder" annotation="LeftShoulder">
              <node name="LeftArm" path="/RootNode/BVH:reference/Hips/LowerBack/Spine/Spine1/LeftShoulder/LeftArm" annotation="LeftArm">
                <node name="LeftForeArm" path="/RootNode/BVH:reference/Hips/LowerBack/Spine/Spine1/LeftShoulder/LeftArm/LeftForeArm" annotation="LeftForeArm">
                  <node name="LeftHand" path="/RootNode/BVH:reference/Hips/LowerBack/Spine/Spine1/LeftShoulder/LeftArm/LeftForeArm/LeftHand" annotation="LeftHand">
                    <node name="LThumb" path="/RootNode/BVH:reference/Hips/LowerBack/Spine/Spine1/LeftShoulder/LeftArm/LeftForeArm/LeftHand/LThumb" annotation="LeftHandThumb1"/>
                  </node>
                </node>
              </node>
            </node>
            <node name="Neck" path="/RootNode/BVH:reference/Hips/LowerBack/Spine/Spine1/Neck" annotation="Neck">
              <node name="Head" path="/RootNode/BVH:reference/Hips/LowerBack/Spine/Spine1/Neck/Neck1/Head" annotation="Head"/>
            </node>
          </node>
        </node>
      </node>
      <node name="RHipJoint" path="/RootNode/BVH:reference/Hips/RHipJoint" annotation="RightHip">
        <node name="RightUpLeg" path="/RootNode/BVH:reference/Hips/RHipJoint/RightUpLeg" annotation="RightUpLeg">
          <node name="RightLeg" path="/RootNode/BVH:reference/Hips/RHipJoint/RightUpLeg/RightLeg" annotation="RightLeg">
            <node name="RightFoot" path="/RootNode/BVH:reference/Hips/RHipJoint/RightUpLeg/RightLeg/RightFoot" annotation="RightFoot">
              <node name="RightToeBase" path="/RootNode/BVH:reference/Hips/RHipJoint/RightUpLeg/RightLeg/RightFoot/RightToeBase" annotation="RightToeBase"/>
            </node>
          </node>
        </node>
      </node>
      <node name="LHipJoint" path="/RootNode/BVH:reference/Hips/LHipJoint" annotation="LeftHip">
        <node name="LeftUpLeg" path="/RootNode/BVH:reference/Hips/LHipJoint/LeftUpLeg" annotation="LeftUpLeg">
          <node name="LeftLeg" path="/RootNode/BVH:reference/Hips/LHipJoint/LeftUpLeg/LeftLeg" annotation="LeftLeg">
            <node name="LeftFoot" path="/RootNode/BVH:reference/Hips/LHipJoint/LeftUpLeg/LeftLeg/LeftFoot" annotation="LeftFoot">
              <node name="LeftToeBase" path="/RootNode/BVH:reference/Hips/LHipJoint/LeftUpLeg/LeftLeg/LeftFoot/LeftToeBase" annotation="LeftToeBase"/>
            </node>
          </node>
        </node>
      </node>
    </node>
  </annotation>
</scene>

=== Vaek/MotionClassification/MotionClassification/skeleton.xml
<?xml version="1.0"?>
<!DOCTYPE scene SYSTEM "scene.dtd">
<scene source_fbx="skeleton.fbx">
	<structure>
		<node name="RootNode" path="/RootNode" annotation="None">
			<node name="mixamorig:Hips" path="/RootNode/mixamorig:Hips" annotation="None">
				<node name="mixamorig:RightUpLeg" path="/RootNode/mixamorig:Hips/mixamorig:RightUpLeg" annotation="None">
					<node name="mixamorig:RightLeg" path="/RootNode/mixamorig:Hips/mixamorig:RightUpLeg/mixamorig:RightLeg" annotation="None">
						<node name="mixamorig:RightFoot" path="/RootNode/mixamorig:Hips/mixamorig:RightUpLeg/mixamorig:RightLeg/mixamorig:RightFoot" annotation="None">
							<node name="mixamorig:RightToeBase" path="/RootNode/mixamorig:Hips/mixamorig:RightUpLeg/mixamorig:RightLeg/mixamorig:RightFoot/mixamorig:RightToeBase" annotation="None">
								<node name="mixamorig:RightToe_End" path="/RootNode/mixamorig:Hips/mixamorig:RightUpLeg/mixamorig:RightLeg/mixamorig:RightFoot/mixamorig:RightToeBase/mixamorig:RightToe_End" annotation="None" />
							</node>
						</node>
					</node>
				</node>
				<node name="mixamorig:LeftUpLeg" path="/RootNode/mixamorig:Hips/mixamorig:LeftUpLeg" annotation="None">
					<node name="mixamorig:LeftLeg" path="/RootNode/mixamorig:Hips/mixamorig:LeftUpLeg/mixamorig:LeftLeg" annotation="None">
						<node name="mixamorig:LeftFoot" path="/RootNode/mixamorig:Hips/mixamorig:LeftUpLeg/mixamorig:LeftLeg/mixamorig:LeftFoot" annotation="None">
							<node name="mixamorig:LeftToeBase" path="/RootNode/mixamorig:Hips/mixamorig:LeftUpLeg/mixamorig:LeftLeg/mixamorig:LeftFoot/mixamorig:LeftToeBase" annotation="None">
								<node name="mixamorig:LeftToe_End" path="/RootNode/mixamorig:Hips/mixamorig:LeftUpLeg/mixamorig:LeftLeg/mixamorig:LeftFoot/mixamorig:LeftToeBase/mixamorig:LeftToe_End" annotation="None" />
							</node>
						</node>
					</node>
				</node>
				<node name="mixamorig:Spine" path="/RootNode/mixamorig:Hips/mixamorig:Spine" annotation="None">
					<node name="mixamorig:Spine1" path="/RootNode/mixamorig:Hips/mixamorig:Spine/mixamorig:Spine1" annotation="None">
						<node name="mixamorig:Spine2" path="/RootNode/mixamorig:Hips/mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2" annotation="None">
							<node name="mixamorig:RightShoulder" path="/RootNode/mixamorig:Hips/mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2/mixamorig:RightShoulder" annotation="None">
								<node name="mixamorig:RightArm" path="/RootNode/mixamorig:Hips/mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2/mixamorig:RightShoulder/mixamorig:RightArm" annotation="None">
									<node name="mixamorig:RightForeArm" path="/RootNode/mixamorig:Hips/mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2/mixamorig:RightShoulder/mixamorig:RightArm/mixamorig:RightForeArm" annotation="None">
										<node name="mixamorig:RightHand" path="/RootNode/mixamorig:Hips/mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2/mixamorig:RightShoulder/mixamorig:RightArm/mixamorig:RightForeArm/mixamorig:RightHand" annotation="None">
											<node name="mixamorig:RightHandIndex1" path="/RootNode/mixamorig:Hips/mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2/mixamorig:RightShoulder/mixamorig:RightArm/mixamorig:RightForeArm/mixamorig:RightHand/mixamorig:RightHandIndex1" annotation="None">
												<node name="mixamorig:RightHandIndex2" path="/RootNode/mixamorig:Hips/mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2/mixamorig:RightShoulder/mixamorig:RightArm/mixamorig:RightForeArm/mixamorig:RightHand/mixamorig:RightHandIndex1/mixamorig:RightHandIndex2" annotation="None">
													<node name="mixamorig:RightHandIndex3" path="/RootNode/mixamorig:Hips/mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2/mixamorig:RightShoulder/mixamorig:RightArm/mixamorig:RightForeArm/mixamorig:RightHand/mixamorig:RightHandIndex1/mixamorig:RightHandIndex2/mixamorig:RightHandIndex3" annotation="None">
														<node name="mixamorig:RightHandIndex4" path="/RootNode/mixamorig:Hips/mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2/mixamorig:RightShoulder/mixamorig:RightArm/mixamorig:RightForeArm/mixamorig:RightHand/mixamorig:RightHandIndex1/mixamorig:RightHandIndex2/mixamorig:RightHandIndex3/mixamorig:RightHandIndex4" annotation="None" />
													</node>
												</node>
											</node>
										</node>
									</node>
								</node>
							</node>
							<node name="mixamorig:LeftShoulder" path="/RootNode/mixamorig:Hips/mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2/mixamorig:LeftShoulder" annotation="None">
								<node name="mixamorig:LeftArm" path="/RootNode/mixamorig:Hips/mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2/mixamorig:LeftShoulder/mixamorig:LeftArm" annotation="None">
									<node name="mixamorig:LeftForeArm" path="/RootNode/mixamorig:Hips/mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2/mixamorig:LeftShoulder/mixamorig:LeftArm/mixamorig:LeftForeArm" annotation="None">
										<node name="mixamorig:LeftHand" path="/RootNode/mixamorig:Hips/mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2/mixamorig:LeftShoulder/mixamorig:LeftArm/mixamorig:LeftForeArm/mixamorig:LeftHand" annotation="None">
											<node name="mixamorig:LeftHandIndex1" path="/RootNode/mixamorig:Hips/mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2/mixamorig:LeftShoulder/mixamorig:LeftArm/mixamorig:LeftForeArm/mixamorig:LeftHand/mixamorig:LeftHandIndex1" annotation="None">
												<node name="mixamorig:LeftHandIndex2" path="/RootNode/mixamorig:Hips/mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2/mixamorig:LeftShoulder/mixamorig:LeftArm/mixamorig:LeftForeArm/mixamorig:LeftHand/mixamorig:LeftHandIndex1/mixamorig:LeftHandIndex2" annotation="None">
													<node name="mixamorig:LeftHandIndex3" path="/RootNode/mixamorig:Hips/mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2/mixamorig:LeftShoulder/mixamorig:LeftArm/mixamorig:LeftForeArm/mixamorig:LeftHand/mixamorig:LeftHandIndex1/mixamorig:LeftHandIndex2/mixamorig:LeftHandIndex3" annotation="None">
														<node name="mixamorig:LeftHandIndex4" path="/RootNode/mixamorig:Hips/mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2/mixamorig:LeftShoulder/mixamorig:LeftArm/mixamorig:LeftForeArm/mixamorig:LeftHand/mixamorig:LeftHandIndex1/mixamorig:LeftHandIndex2/mixamorig:LeftHandIndex3/mixamorig:LeftHandIndex4" annotation="None" />
													</node>
												</node>
											</node>
										</node>
									</node>
								</node>
							</node>
							<node name="mixamorig:Neck" path="/RootNode/mixamorig:Hips/mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2/mixamorig:Neck" annotation="None">
								<node name="mixamorig:Head" path="/RootNode/mixamorig:Hips/mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2/mixamorig:Neck/mixamorig:Head" annotation="None">
									<node name="mixamorig:HeadTop_End" path="/RootNode/mixamorig:Hips/mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2/mixamorig:Neck/mixamorig:Head/mixamorig:HeadTop_End" annotation="None" />
								</node>
							</node>
						</node>
					</node>
				</node>
			</node>
			<node name="sub02" path="/RootNode/sub02" annotation="None" />
			<node name="sub01" path="/RootNode/sub01" annotation="None" />
		</node>
	</structure>
</scene>
